all: main

main:
	echo Compiling Global.java ...
	javac Global.java

test:
	echo Compiling GlobalTest.java ...
	javac GlobalTest.java
	echo Running Unit Tests on Global.java
	java GlobalTest

clean:
	rm -rf *.class